import type { Metadata } from "next";
import "@styles/globals.css"
import { ReactNode } from "react";
import { CustomProvider } from 'rsuite';


// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className="text-[var(--black)] w-[100vw] h-[100vh]">
                {children}
            </body>
        </html>
    );
}
